name: yield_v1
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - comm=0.2.2
  - debugpy=1.8.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libsodium=1.0.20
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.11.10
  - python-dateutil=2.9.0
  - python_abi=3.11
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - pip:
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.6
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - attrs==24.2.0
      - beautifulsoup4==4.12.3
      - bertopic==0.17.0
      - bitsandbytes==0.44.1
      - blis==1.3.0
      - catalogue==2.0.10
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.2.1
      - cloudpathlib==0.21.1
      - confection==0.1.5
      - contourpy==1.3.2
      - cycler==0.12.1
      - cymem==2.0.11
      - datasets==3.1.0
      - deepspeed==0.16.0
      - dill==0.3.8
      - en-core-web-sm==3.8.0
      - filelock==3.16.1
      - fonttools==4.58.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - greenlet==3.1.1
      - hdbscan==0.8.40
      - hjson==3.1.0
      - huggingface-hub==0.26.2
      - idna==3.10
      - inflect==7.5.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - language-data==1.3.0
      - llvmlite==0.44.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - murmurhash==1.0.13
      - narwhals==1.41.0
      - networkx==3.4.2
      - ninja==1.11.1.2
      - numba==0.61.2
      - numpy==2.1.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.4.127
      - pandas==2.2.3
      - peft==0.13.2
      - pillow==11.0.0
      - playwright==1.48.0
      - plotly==6.1.2
      - preshed==3.0.10
      - propcache==0.2.0
      - py-cpuinfo==9.0.0
      - pyarrow==18.0.0
      - pydantic==2.10.2
      - pydantic-core==2.27.1
      - pyee==12.0.0
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - rich==14.0.0
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - sentence-transformers==3.2.1
      - shellingham==1.5.4
      - smart-open==7.1.0
      - soupsieve==2.6
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - sympy==1.13.1
      - thinc==8.3.6
      - threadpoolctl==3.5.0
      - tokenizers==0.20.1
      - torch==2.5.1+cu118
      - torchaudio==2.5.1+cu118
      - torchvision==0.20.1+cu118
      - tqdm==4.66.6
      - transformers==4.46.1
      - triton==3.1.0
      - trl==0.17.0
      - typeguard==4.4.2
      - typer==0.16.0
      - tzdata==2024.2
      - umap-learn==0.5.7
      - urllib3==2.2.3
      - wasabi==1.1.3
      - weasel==0.4.1
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.17.2
